[package]
name = "stylus-hello-world-minimal"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk = "0.4.2"
mini-alloc = "0.4.2"

[features]
export-abi = ["stylus-sdk/export-abi"]

[lib]
crate-type = ["lib", "cdylib"]

[workspace]
